server:
  port: 8001

spring:
  application:
    name: weshow-service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #mysql驱动
    url: jdbc:mysql://159.75.85.125:3306/weshow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Gqb6666.
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.112.187:1111 #nacos集群地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gqb.user.entity  #所有Entity别名类所在包

pagehelper:
  reasonable: true
  params: count=countSql
  helper-dialect: mysql
  support-methods-arguments: true

management:
  endpoints:
    web:
      exposure:
        include: '*'